name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened, closed]
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build-dotnet:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    permissions:
      contents: read
      actions: write
      security-events: write

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
  
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: csharp
        queries: +security-and-quality
        config-file: ./.github/codeql/codeql-config.yml
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # commit hash for v2

    - name: Restore nuget dependencies
      run: dotnet restore --ignore-failed-sources

    - name: Build API
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /m

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4

  build-react:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    permissions:
      contents: read
      actions: write
      security-events: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
  
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: checkmate-web/package-lock.json

    - name: npm ci
      run: npm ci
      working-directory: ./checkmate-web

    - name: npm run lint
      run: npm run lint
      working-directory: ./checkmate-web

    - name: npm run type-check
      run: npm run type-check
      working-directory: ./checkmate-web

    - name: npm run format:check
      run: npm run format:check
      working-directory: ./checkmate-web

    - name: npm run build
      run: npm run build
      working-directory: ./checkmate-web

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: javascript-typescript
        build-mode: none
        queries: +security-and-quality
        config-file: ./.github/codeql/codeql-react-config.yml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4

    - name: Deploy to Azure Static Web Apps
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
        action: "upload"
        skip_app_build: true
        app_location: "./checkmate-web"
        output_location: "/out"
        repo_token: ${{ secrets.GITHUB_TOKEN }}

  build-actions:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    permissions:
      contents: read
      actions: write
      security-events: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
  
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: actions
        queries: +security-and-quality
  
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    runs-on: ubuntu-latest

    steps:
      - name: Clean up Preview Static Site
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          action: "close"