name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore nuget dependencies
      run: dotnet restore --ignore-failed-sources

    - name: Build API
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /m

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: checkmate-web/package-lock.json

    - name: Install npm dependencies
      run: npm ci
      working-directory: ./checkmate-web

    - name: Run ESLint
      run: npm run lint
      working-directory: ./checkmate-web

    - name: Check TypeScript types
      run: npm run type-check
      working-directory: ./checkmate-web

    - name: Check code formatting
      run: npm run format:check
      working-directory: ./checkmate-web

    - name: Build React project
      run: npm run build
      working-directory: ./checkmate-web
